#!/bin/bash

curl -L https://bootstrap.saltstack.com | bash install_salt.sh

service salt-minion stop
chkconfig --del salt-minion

pip install --upgrade boto3

sed -i 's/^#* *file_client:.*$/file_client: local/' /etc/salt/minion

